/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CampaignColorSelectorNode: typeof import('./components/campaign/color-selector-node.vue')['default']
    CampaignOutputNode: typeof import('./components/campaign/output-node.vue')['default']
    RouteBack: typeof import('./components/route-back.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBreadcrumbs: typeof import('./components/ui/breadcrumbs.vue')['default']
    UiButton: typeof import('./components/ui/button.vue')['default']
    UiButtonToggle: typeof import('./components/ui/button-toggle.vue')['default']
    UiCheckbox: typeof import('./components/ui/checkbox.vue')['default']
    UiContextMenu: typeof import('./components/ui/context-menu.vue')['default']
    UiInput: typeof import('./components/ui/input.vue')['default']
    UiMenu: typeof import('./components/ui/menu.vue')['default']
    UiModal: typeof import('./components/ui/modal.vue')['default']
    UiNumberPicker: typeof import('./components/ui/number-picker.vue')['default']
    UiRadio: typeof import('./components/ui/radio.vue')['default']
    UiResizingBlocks: typeof import('./components/ui/resizing-blocks.vue')['default']
    UiSelect: typeof import('./components/ui/select.vue')['default']
    UiSeparator: typeof import('./components/ui/separator.vue')['default']
    UiSidePanel: typeof import('./components/ui/side-panel.vue')['default']
    UiSpinner: typeof import('./components/ui/spinner.vue')['default']
    UiTable: typeof import('./components/ui/table.vue')['default']
    UiTabs: typeof import('./components/ui/tabs.vue')['default']
  }
}
